Add functioning tests to activated entities
eivindkopperud/master-thesis pull request #21
Opened 2022-04-29 13:49 UTC by TheodorRene

The tests don't run, but will someday

2022-04-29 13:49 UTC, TheodorRene commented on data-generation/src/test/scala/SnapshotDeltaSpec.scala
> -import thesis.{LogTSV, Snapshot, SnapshotDeltaObject}
wops

2022-04-30 15:22 UTC, eivindkopperud approved these changes
Very nice!

2022-04-30 15:22 UTC, eivindkopperud commented on data-generation/src/test/scala/SnapshotDeltaSpec.scala
> +    assert(intervalWithV2andEdge._1.take(1).head == 1L && intervalWithV1andEdge._2.count() == 1)
```suggestion
    assert(intervalWithV2andEdge._1.take(1).head == 1L && intervalWithV2andEdge._2.count() == 1)
```

2022-04-30 15:22 UTC, eivindkopperud commented on data-generation/src/test/scala/SnapshotDeltaSpec.scala
> +    assert(intervalWithAll._1.collect().toSet == Set(1L, 2L) && intervalWithV1andEdge._2.count() == 1)
```suggestion
    assert(intervalWithAll._1.collect().toSet == Set(1L, 2L) && intervalWithAll._2.count() == 1)
```

2022-05-01 11:44 UTC, eivindkopperud commented on data-generation/src/test/scala/SnapshotDeltaSpec.scala
> +    val intervalWithVertex2 = g.activatedEntities(Interval(5, 7))
```suggestion
    val intervalWithVertex2 = g.activatedEntities(Interval(9, 10))
```
For å ikke aktivere edgen

2022-05-01 15:31 UTC, eivindkopperud requested changes
Intervallene Interval(1, 10) blir faktisk evaluert likt som Interval(1, 1), fordi 1->10 er så sinnsykt lite i epoch time. Så vi burde gjøre noe á la jeg har gjort i #23

2022-05-02 09:31 UTC, TheodorRene commented
> Intervallene Interval(1, 10) blir faktisk evaluert likt som Interval(1, 1), fordi 1->10 er så sinnsykt lite i epoch time. Så vi burde gjøre noe á la jeg har gjort i #23

Men ikke nå lenger vel? Det var vel problemet før, etter du fikset det i #25. 1 ->10 skal være 10 sekunder det. Alt er relativt, men det er ganske mye det.

2022-05-02 09:46 UTC, eivindkopperud commented
> Det var vel problemet før, etter du fikset det i #25. 1 ->10 skal være 10 sekunder det. 

Hmm not sure, lager samme test cases i #23 og tror jeg hadde de problemene der, men kan hende det var et helt annet underliggende problem som jeg glemte at jeg fikset.

Det er også mye logikk i disse tidsintervallene. Lurer på om det kan være greit å splitte opp i test for activated edges og activated vertices for å gjøre de litt lettere å lese, og litt mindre utsatte for feil ved å glippe på intervallene.

2022-05-02 09:50 UTC, TheodorRene commented
> > Det var vel problemet før, etter du fikset det i #25. 1 ->10 skal være 10 sekunder det.
> 
> Hmm not sure, lager samme test cases i #23 og tror jeg hadde de problemene der, men kan hende det var et helt annet underliggende problem som jeg glemte at jeg fikset.

Ja, siden 10 sekunder interval burde gå helt fint det. I en ekte applikasjon skal den jo tåle mye mindre intervaller. Og man tar 1.januar 1970 eller 22.april 2021 skal funksjonene funkte like bra 

> Det er også mye logikk i disse tidsintervallene. Lurer på om det kan være greit å splitte opp i test for activated edges og activated vertices for å gjøre de litt lettere å lese, og litt mindre utsatte for feil ved å glippe på intervallene (også relatert til #24 )

Ja, jeg hadde helt utrolig mange logikkfeil. Enda flere enn du fikset. Så kunne nok trengt en refakturering.

2022-05-02 10:01 UTC, eivindkopperud approved these changes
Looks good (gitt at testene passerer seff)🚀

2022-05-02 10:21 UTC, merged